# Replace HelloWorld with the name of your Java file, sans extension. For
# example, if you were working with a Java file called, Assignment2.java, then
# replace “HelloWorld” with “Assignment2”.

filename = HelloWorld

all: compile run

compile:
	javac $(filename).java

run:
	java $(filename)

clean:
	rm $(filename).class
